name             'whyrun_execute'
maintainer       'sonots'
maintainer_email 'sonots@gmail.com'
license          'All rights reserved'
description      'Installs/Configures whyrun_execute'
long_description 'Installs/Configures whyrun_execute'
version          '0.1.0'
